const { FONT_FACES } = require('../design-system');
const { iconDataUri } = require('../icons');

// Subtle, asset-free background textures (pure CSS) keyed by spec.texture.
function textureCss(t) {
  if (t.treatment !== 'texture') return '';
  const ink = t.mode === 'dark' ? 'rgba(255,255,255,0.035)' : 'rgba(80,55,35,0.05)';
  const patterns = {
    weave: `background-image:
      repeating-linear-gradient(45deg, ${ink} 0 2px, transparent 2px 10px),
      repeating-linear-gradient(-45deg, ${ink} 0 2px, transparent 2px 10px);`,
    dots: `background-image: radial-gradient(${ink} 1.2px, transparent 1.3px);
      background-size: 16px 16px;`,
    grid: `background-image:
      linear-gradient(${ink} 1px, transparent 1px),
      linear-gradient(90deg, ${ink} 1px, transparent 1px);
      background-size: 22px 22px;`,
  };
  return `\n  ${patterns[t.texture || 'dots']}\n  background-attachment: fixed;`;
}

function rootVars(t) {
  return Object.entries(t.vars).map(([k, v]) => `  ${k}: ${v};`).join('\n');
}

function skeletonAuto(t) {
  const headingCase = t.uppercase ? 'uppercase' : 'none';
  const headingSpacing = t.uppercase ? '0.18rem' : '0.005em';
  return `/* ${t.name} — generated by theme-toolkit. Edit the spec, not this file. */

.container { position: relative; width: 100%; max-width: 600px; text-align: center; margin: 0 auto; box-sizing: border-box; }
.column { position: center; width: 100%; box-sizing: border-box; }
@media (min-width: 400px) { .container { width: 85%; padding: 0; } }
@media (min-width: 550px) { .container { width: 80%; } .column, .columns { margin-left: 0; } }

html { font-size: 100%; }

:root {
${rootVars(t)}
}

::selection { background: var(--accent-color); color: #fff; }
::-moz-selection { background: var(--accent-color); color: #fff; }

body {
  min-height: 100vh;
  font-family: var(--font-family) !important;
  background-color: var(--background-color);
  color: var(--title-color);
  background-position: center;
  background-repeat: no-repeat;
  font-size: var(--font-size);
  line-height: 1.6;
  font-weight: 400;${textureCss(t)}
}

.background { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; }

h1 {
  color: var(--title-color);
  font-family: var(--heading-font-family);
  font-size: 2.1em;
  font-weight: ${t.headingWeight};
  letter-spacing: ${headingSpacing};
  text-transform: ${headingCase};
  line-height: 1.15;
  margin-bottom: 0.2em;
}

p {
  color: var(--description-color);
  font-size: 1.05em;
  line-height: 1.6em;
  font-weight: 400;
  margin-bottom: 10px;
  letter-spacing: 0.005em;
}

a { color: var(--title-color); text-decoration: none; }
a:hover { color: var(--button-text-hover-color); }

.spacing { padding: 0 10px; padding-top: 50px; }

button, .button { margin-bottom: 1rem; display: block !important; }
input, textarea, select, fieldset { margin-bottom: 1.5rem; }
pre, blockquote, dl, figure, p, ol { margin-bottom: 2.5rem; }

.u-full-width { width: 100%; box-sizing: border-box; }
.u-max-full-width { max-width: 100%; box-sizing: border-box; }

* { -ms-overflow-style: none; scrollbar-width: none; }
*::-webkit-scrollbar { display: none; }

.credit-txt { font-weight: 700; font-size: 15px; text-decoration: none; }
.credit-icon { display: none; }
.credit-footer { position: relative; }
.credit-txt-clr { color: var(--footer-text-color) !important; }
`;
}

function brands(t) {
  const b = t.button;
  const baseBorderColor = t.mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.07)';
  let borderRules;
  if (b.borderSide === 'all') {
    borderRules = `  border: ${b.border};`;
    if (b.accentBar) borderRules = `  border: ${b.border};\n  border-left: 4px solid ${b.accentBar};`;
  } else if (b.borderSide === 'left') {
    borderRules = `  border: 1px solid ${baseBorderColor};\n  border-left: ${b.border};`;
  } else { // bottom
    borderRules = `  border: 1px solid ${baseBorderColor};\n  border-bottom: ${b.border};`;
  }
  return `/* ${t.name} — buttons, avatar, brand icons. Generated. */

.rounded-avatar {
  border-radius: 50%;
  box-shadow: 0 0 0 3px ${t.avatarRing};
  background-color: var(--button-background-color) !important;
  width: var(--image-width);
  height: var(--image-height);
}

.social-icon { font-size: 30px; padding: 9px; }
.social-icon-div { padding-bottom: 28px; }
.social-icon { color: var(--svg-color); }
.social-icon:hover { color: var(--accent-color); }

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  text-decoration: none;
  font-size: 1em;
  min-height: 56px;
  line-height: 1.2;
  cursor: pointer;
  color: var(--button-text-color);
  background-color: var(--button-background-color);
  width: 100%;
  max-width: 600px;
  border-radius: ${t.shape};
${borderRules}
  margin-bottom: 16px !important;
  font-weight: 500;
  letter-spacing: 0.01em;
  transition: transform 0.18s ease, border-color 0.18s ease, color 0.18s ease;
  transform: translateZ(0);
}
.button:hover {
  color: var(--button-text-hover-color);
  border-color: var(--accent-color);
  transform: translateY(-2px);
}

.icon {
  right: 10px; bottom: 2px; position: relative; vertical-align: middle;
  width: 20px; height: 20px;
}
`;
}

function animations() {
  return `/* Generated theme animations — gentle entrance + button lift. */

.button-hover, .credit-hover {
  display: inline-block;
  transform: perspective(1px) translateZ(0);
  transition-duration: .1s;
  transition-property: transform;
}
.button-hover:active, .button-hover:focus, .button-hover:hover { transform: scale(1.02); }
.credit-hover:active, .credit-hover:focus, .credit-hover:hover { transform: scale(1.04); }

.footer-hover {
  display: inline-block;
  transform: perspective(1px) translateZ(0);
  transition-duration: .3s;
  transition-property: transform;
  transition-timing-function: ease-out;
}
.footer-hover:active, .footer-hover:focus, .footer-hover:hover { transform: translateY(-6px); }

@keyframes fadein { from { opacity: 0; transform: translateY(-8px); } to { opacity: 1; transform: translateY(0); } }
.fadein { animation: fadein 0.6s ease both; }
`;
}

function shareButton(t) {
  return `/* ${t.name} — share button + toast. Generated. */

.share-icon { padding: 0 5px 3.5px 0; vertical-align: middle; width: 20px; height: 20px; color: var(--svg-color); }
.sharediv { position: relative; top: 30px; right: 30px; padding-bottom: 40px; }
.toastdiv { display: flex; align-items: center; justify-content: center; }
.toastbox {
  width: 280px; padding: 10px; background-color: rgba(0,0,0,0.78); color: #fff;
  border-radius: 8px; position: fixed; top: 105%; transition: transform .3s linear;
  z-index: 2; text-align: center;
}
.toastbox.toast-tox--active { transform: translateY(-150px); }

.sharebutton, sharebutton {
  display: inline-block; text-decoration: none; height: 48px; width: 48px;
  text-align: center; vertical-align: middle; font-size: 18px; font-weight: 700;
  line-height: 48px; letter-spacing: 0.1px;
  border: solid var(--accent-color) 2px; border-radius: ${t.shape === '999px' ? '999px' : '10px'};
  cursor: pointer; color: var(--button-text-color); background-color: var(--button-background-color);
  transition: transform .18s ease;
}
.sharebutton:hover { transform: translateY(-2px); }
.sharebutton-mb { display: none; }
.sharebutton-img { position: relative; left: 3px; margin-left: auto; margin-right: auto; }
`;
}

function fontFaceBlocks(t) {
  const families = [...new Set([t.headingFont, t.bodyFont])];
  const blocks = [];
  for (const fam of families) {
    for (const [file, weight] of FONT_FACES[fam]) {
      blocks.push(
`@font-face {
  font-family: '${fam}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url("{{ themeAsset('${file}.woff2') }}") format('woff2');
}`);
    }
  }
  return blocks.join('\n');
}

function customHead(t) {
  let bg = '';
  if (t.treatment === 'photo' && t.background) {
    const scrim = t.scrim === 'dark'
      ? 'linear-gradient(180deg, rgba(8,8,10,0.55), rgba(8,8,10,0.78))'
      : 'linear-gradient(180deg, rgba(255,250,242,0.62), rgba(250,243,232,0.84))';
    bg =
`\nbody {
  background-image: ${scrim}, url("{{ themeAsset('${t.background}') }}");
  background-size: cover, cover;
  background-position: center, center;
  background-attachment: fixed, fixed;
  background-repeat: no-repeat, no-repeat;
}`;
  }
  let motif = '';
  if (t.icon) {
    // Faint profession glyph behind the content so the theme reads as its
    // trade. Photo themes already signal, so dial the motif down on them.
    const uri = iconDataUri(t.icon, t.vars['--title-color']);
    const opacity = t.mode === 'dark' ? 0.05 : 0.06;
    motif =
`\nbody::before {
  content: "";
  position: fixed;
  inset: 0;
  z-index: -1;
  pointer-events: none;
  background-image: url("${uri}");
  background-repeat: repeat;
  background-position: center;
  background-size: 78px;
  opacity: ${opacity};
}`;
  }
  return `<style>
${fontFaceBlocks(t)}
${bg}${motif}
</style>
`;
}

module.exports = { skeletonAuto, brands, animations, shareButton, customHead };
