#!/usr/bin/env node
// Generate theme folders from themes.js into ../themes/<slug>/.
// Usage: node build.js [slug ...]   (no args = build all)

const fs = require('fs');
const path = require('path');
const { resolve } = require('./design-system');
const css = require('./lib/css');
const SPECS = require('./themes');

const ROOT = path.resolve(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const FONTS_DIR = path.join(__dirname, 'fonts');
const BG_DIR = path.join(__dirname, 'backgrounds');

function configPhp(t) {
  return `<?php

return [
    'allow_custom_buttons' => 'false',
    'open_links_in_same_tab' => 'false',
    'enable_custom_code' => 'true',
    'enable_custom_head'     => 'true',
    'enable_custom_body'     => 'false',
    'enable_custom_body_end' => 'false',
    'use_custom_icons' => 'false',
    'custom_icon_extension' => '.svg',
];
`;
}

function readmeMd(t) {
  return `# A Mail Minted Theme

*\tTheme Name: ${t.name}
*\tTheme Category: ${t.category}
*\tTheme Version: 1.0
*\tTheme Author: Mail Minted

${t.blurb}

Built from the Mail Minted theme design system (archetype: ${t.archetype}, accent: ${t.accent}).
Fonts self-hosted under MIT/OFL licenses. Generated by theme-toolkit.
`;
}

function write(p, c) { fs.writeFileSync(p, c); }

function build(spec) {
  const t = resolve(spec);
  const dir = path.join(THEMES_DIR, t.slug);
  const assets = path.join(dir, 'extra', 'custom-assets');
  const icons = path.join(dir, 'extra', 'custom-icons');
  fs.mkdirSync(assets, { recursive: true });
  fs.mkdirSync(icons, { recursive: true });

  write(path.join(dir, 'config.php'), configPhp(t));
  write(path.join(dir, 'readme.md'), readmeMd(t));
  write(path.join(dir, 'skeleton-auto.css'), css.skeletonAuto(t));
  write(path.join(dir, 'brands.css'), css.brands(t));
  write(path.join(dir, 'animations.css'), css.animations(t));
  write(path.join(dir, 'share.button.css'), css.shareButton(t));
  write(path.join(dir, 'extra', 'custom-head.blade.php'), css.customHead(t));

  // Self-host the font files this theme uses.
  const files = new Set();
  for (const f of t.font.files) files.add(f);
  for (const f of files) {
    const src = path.join(FONTS_DIR, `${f}.woff2`);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(assets, `${f}.woff2`));
    else console.warn(`  ! missing font ${f}.woff2`);
  }

  // Photo themes: ship their background if present.
  let note = t.treatment;
  if (t.treatment === 'photo' && t.background) {
    const src = path.join(BG_DIR, t.background);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(assets, t.background));
    else note = `photo (BACKGROUND MISSING: drop ${t.background} in theme-toolkit/backgrounds/)`;
  }
  console.log(`✓ ${t.slug}  [${t.archetype} · ${t.accent} · ${note}]`);
}

const want = process.argv.slice(2);
const specs = want.length ? SPECS.filter(s => want.includes(s.slug)) : SPECS;
if (!specs.length) { console.error('No matching themes.'); process.exit(1); }
fs.mkdirSync(THEMES_DIR, { recursive: true });
specs.forEach(build);
console.log(`\nBuilt ${specs.length} theme(s) into themes/.`);
