#!/usr/bin/env node
// Generate theme folders from themes.js into ../themes/<slug>/.
// Usage: node build.js [slug ...]   (no args = build all)

const fs = require('fs');
const path = require('path');
const { resolve } = require('./design-system');
const css = require('./lib/css');
const SPECS = require('./themes');

const ROOT = path.resolve(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const FONTS_DIR = path.join(__dirname, 'fonts');
const BG_DIR = path.join(__dirname, 'backgrounds');

function configPhp(t) {
  return `<?php

return [
    'allow_custom_buttons' => 'false',
    'open_links_in_same_tab' => 'false',
    'enable_custom_code' => 'true',
    'enable_custom_head'     => 'true',
    'enable_custom_body'     => 'false',
    'enable_custom_body_end' => 'false',
    'use_custom_icons' => 'false',
    'custom_icon_extension' => '.svg',
];
`;
}

function readmeMd(t) {
  return `# A Mail Minted Theme

*\tTheme Name: ${t.name}
*\tTheme Category: ${t.category}
*\tTheme Version: 1.0
*\tTheme Author: Mail Minted

${t.blurb}

Built from the Mail Minted theme design system (archetype: ${t.archetype}, accent: ${t.accent}).
Fonts self-hosted under MIT/OFL licenses. Generated by theme-toolkit.
`;
}

// Appearance manifest — the theme's canonical values in the exact shape
// of users.theme_customization (see AppearanceController::defaults()).
// Phase 1 of THEME-APPEARANCE-PLAN.md: the studio editor hydrates its
// controls from this so the knobs show the theme's truth, and saves
// diff against it so only real changes are stored as overrides.
function themeJson(t) {
  // px radius → appearance blob shape name (999px pill / 14px soft /
  // 4px sharp map onto the editor's pill / rounded / square knobs).
  const shapeName = { '999px': 'pill', '14px': 'rounded', '4px': 'square' }[t.shape] || 'rounded';
  // White-bodied buttons read as outline, dark-filled as filled. This
  // is a display-only approximation: sparse saves never emit button
  // CSS unless the user actually changes a button knob, so the theme's
  // real treatment (accent side-bars etc.) survives untouched.
  const styleName = t.button.bg.toUpperCase() === '#FFFFFF' ? 'outline' : 'filled';
  const background = t.treatment === 'photo' && t.background
    ? { type: 'image', image_url: `/themes/${t.slug}/extra/custom-assets/${t.background}`, solid: t.vars['--background-color'] }
    : { type: 'solid', solid: t.vars['--background-color'] };
  // The REAL resting button look as one self-contained declaration
  // string (concrete hexes — consumers don't load the theme's CSS
  // vars). The studio block editor paints its sample button with this
  // while the block is following the theme, so the preview shows the
  // theme's true treatment (accent side-bars etc.), not the
  // filled/outline approximation above. Mirrors lib/css.js brands().
  const baseBorderColor = t.mode === 'dark' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.07)';
  let borderCss;
  if (t.button.borderSide === 'all') {
    borderCss = `border: ${t.button.border};`;
    if (t.button.accentBar) borderCss += ` border-left: 4px solid ${t.button.accentBar};`;
  } else if (t.button.borderSide === 'left') {
    borderCss = `border: 1px solid ${baseBorderColor}; border-left: ${t.button.border};`;
  } else { // bottom
    borderCss = `border: 1px solid ${baseBorderColor}; border-bottom: ${t.button.border};`;
  }
  const buttonCss = `background-color: ${t.button.bg}; color: ${t.button.text}; ${borderCss} border-radius: ${t.shape};`;
  return JSON.stringify({
    _meta: {
      generated: 'by theme-toolkit build.js — do not edit by hand',
      archetype: t.archetype,
      mode: t.mode,
      heading_font: t.headingFont,
      body_font: t.bodyFont,
      button_css: buttonCss,
    },
    colors: {
      primary: t.accent,
      background: t.vars['--background-color'],
      text: t.vars['--title-color'],
      button_text: t.button.text,
    },
    background,
    // '' = the theme's own self-hosted pairing ("Theme default" in the
    // font picker). A Google-font pick is always an explicit override.
    typography: { font: '' },
    buttons: { shape: shapeName, style: styleName },
    avatar: { shape: 'circle' },
    // The theme styles its own icon row (ink color, its own hover);
    // these are the knob positions that describe it, not overrides.
    social_icons: {
      color: 'auto',
      size: 'medium',
      spacing: 'normal',
      background_style: 'none',
      hover: 'none',
    },
  }, null, 2) + '\n';
}

function write(p, c) { fs.writeFileSync(p, c); }

function build(spec) {
  const t = resolve(spec);
  const dir = path.join(THEMES_DIR, t.slug);
  const assets = path.join(dir, 'extra', 'custom-assets');
  const icons = path.join(dir, 'extra', 'custom-icons');
  fs.mkdirSync(assets, { recursive: true });
  fs.mkdirSync(icons, { recursive: true });

  write(path.join(dir, 'config.php'), configPhp(t));
  write(path.join(dir, 'readme.md'), readmeMd(t));
  write(path.join(dir, 'theme.json'), themeJson(t));
  write(path.join(dir, 'skeleton-auto.css'), css.skeletonAuto(t));
  write(path.join(dir, 'brands.css'), css.brands(t));
  write(path.join(dir, 'animations.css'), css.animations(t));
  write(path.join(dir, 'share.button.css'), css.shareButton(t));
  write(path.join(dir, 'extra', 'custom-head.blade.php'), css.customHead(t));

  // Self-host the font files this theme uses.
  const files = new Set();
  for (const f of t.font.files) files.add(f);
  for (const f of files) {
    const src = path.join(FONTS_DIR, `${f}.woff2`);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(assets, `${f}.woff2`));
    else console.warn(`  ! missing font ${f}.woff2`);
  }

  // Photo themes: ship their background if present.
  let note = t.treatment;
  if (t.treatment === 'photo' && t.background) {
    const src = path.join(BG_DIR, t.background);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(assets, t.background));
    else note = `photo (BACKGROUND MISSING: drop ${t.background} in theme-toolkit/backgrounds/)`;
  }
  console.log(`✓ ${t.slug}  [${t.archetype} · ${t.accent} · ${note}]`);
}

const want = process.argv.slice(2);
const specs = want.length ? SPECS.filter(s => want.includes(s.slug)) : SPECS;
if (!specs.length) { console.error('No matching themes.'); process.exit(1); }
fs.mkdirSync(THEMES_DIR, { recursive: true });
specs.forEach(build);
console.log(`\nBuilt ${specs.length} theme(s) into themes/.`);
